# Generated by Django 4.1.5 on 2023-01-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('room_type', models.CharField(choices=[('DELUXE', 'Deluxe'), ('LUXURY', 'Luxury')], max_length=50)),
                ('floor', models.CharField(max_length=50, null=True)),
                ('ac', models.BooleanField(default=False)),
                ('attached_bathroom', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('furniture', models.BooleanField(default=False)),
                ('smooking', models.BooleanField(default=False)),
                ('room_service', models.BooleanField(default=False)),
                ('king_size_bed_count', models.IntegerField(default=0)),
                ('queen_size_bed_count', models.IntegerField(default=0)),
                ('single_bed_count', models.IntegerField(default=0)),
                ('is_vacant', models.BooleanField(default=True)),
                ('next_vacant_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
