# Generated by Django 4.1.7 on 2023-05-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='discount',
        ),
    ]
