# Generated by Django 4.1.5 on 2023-05-12 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='operation_end_time',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AddField(
            model_name='contact',
            name='operation_start_time',
            field=models.TimeField(default=datetime.time(4, 0)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
