# Generated by Django 4.1.5 on 2023-01-26 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        ('landmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='landmark_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landmark.landmark'),
        ),
    ]
